import { DEMO_PASSWORD } from "./constants";
import type { StoreState } from "./types";

const weekdays: StoreState["movers"][number]["availability"] = [
  { day: 1, start: "08:00", end: "18:00" },
  { day: 2, start: "08:00", end: "18:00" },
  { day: 3, start: "08:00", end: "18:00" },
  { day: 4, start: "08:00", end: "18:00" },
  { day: 5, start: "08:00", end: "18:00" },
  { day: 6, start: "08:00", end: "16:00" },
];

const weekends: StoreState["movers"][number]["availability"] = [
  { day: 0, start: "09:00", end: "16:00" },
  { day: 6, start: "08:00", end: "18:00" },
];

const p = (id: string) =>
  `https://images.unsplash.com/photo-${id}?auto=format&fit=crop&w=400&q=80`;

export const seedState: StoreState = {
  currentUserId: null,
  settings: { serviceFeeRate: 0.08 },
  otp: null,
  adminLog: [
    {
      id: "adm-seed",
      at: "2026-08-18T08:00:00.000Z",
      actorId: "u-admin",
      action: "seed",
      detail: "Canada demo workspace loaded.",
    },
  ],
  users: [
    {
      id: "u-admin",
      name: "Haulsy Admin",
      email: "admin@haulsy.test",
      password: DEMO_PASSWORD,
      phone: "416-555-0000",
      city: "Toronto",
      roles: ["admin"],
    },
    {
      id: "u-madhavi",
      name: "Madhavi Bhatt",
      email: "madhavi.buyer@haulsy.test",
      password: DEMO_PASSWORD,
      phone: "416-555-0101",
      city: "Toronto",
      roles: ["buyer"],
      avatar: p("1544005313-94ddf0286df2"),
    },
    {
      id: "u-mitwa",
      name: "Mitwa Parasana",
      email: "mitwa.buyer@haulsy.test",
      password: DEMO_PASSWORD,
      phone: "905-555-0102",
      city: "Mississauga",
      roles: ["buyer"],
      avatar: p("1580489944761-15a19d654956"),
    },
    {
      id: "u-bhumi",
      name: "Bhumi Patel",
      email: "bhumi.buyer@haulsy.test",
      password: DEMO_PASSWORD,
      phone: "905-555-0103",
      city: "Brampton",
      roles: ["buyer"],
      avatar: p("1534528741775-53994a69daeb"),
    },
    {
      id: "u-rajvi",
      name: "Rajvi Patel",
      email: "rajvi.buyer@haulsy.test",
      password: DEMO_PASSWORD,
      phone: "416-555-0104",
      city: "Toronto",
      roles: ["buyer"],
      avatar: p("1487412720507-e7ab37603c6f"),
    },
    {
      id: "u-heera",
      name: "Heera Singh",
      email: "heera.buyer@haulsy.test",
      password: DEMO_PASSWORD,
      phone: "604-555-0105",
      city: "Vancouver",
      roles: ["buyer"],
      avatar: p("1524504388940-b1c1722653e1"),
    },
    {
      id: "u-dharmesh",
      name: "Dharmesh Patel",
      email: "dharmesh.seller@haulsy.test",
      password: DEMO_PASSWORD,
      phone: "416-555-0201",
      city: "Toronto",
      roles: ["seller", "buyer"],
      avatar: p("1500648767791-00dcc994a43e"),
    },
    {
      id: "u-joy",
      name: "Joy Patel",
      email: "joy.seller@haulsy.test",
      password: DEMO_PASSWORD,
      phone: "905-555-0202",
      city: "Mississauga",
      roles: ["seller"],
      avatar: p("1539571696357-5a69c17a67c6"),
    },
    {
      id: "u-priyenka",
      name: "Priyenka Patel",
      email: "priyenka.seller@haulsy.test",
      password: DEMO_PASSWORD,
      phone: "905-555-0203",
      city: "Brampton",
      roles: ["seller"],
      avatar: p("1438761681033-6461ffad8d80"),
    },
    {
      id: "u-meet",
      name: "Meet Shah",
      email: "meet.seller@haulsy.test",
      password: DEMO_PASSWORD,
      phone: "403-555-0204",
      city: "Calgary",
      roles: ["seller"],
      avatar: p("1507003211169-0a1dd7228f2d"),
    },
    {
      id: "u-aisha",
      name: "Aisha Khan",
      email: "aisha.mover@haulsy.test",
      password: DEMO_PASSWORD,
      phone: "416-555-0301",
      city: "Toronto",
      roles: ["mover", "buyer"],
      avatar: p("1573496359142-b8d87734a5a2"),
    },
    {
      id: "u-sagar",
      name: "Sagar Gondaliya",
      email: "sagar.mover@haulsy.test",
      password: DEMO_PASSWORD,
      phone: "416-555-0302",
      city: "Toronto",
      roles: ["mover"],
      avatar: p("1506794778202-cad84cf45f1d"),
    },
    {
      id: "u-chirag",
      name: "Chirag Patel",
      email: "chirag.mover@haulsy.test",
      password: DEMO_PASSWORD,
      phone: "905-555-0303",
      city: "Brampton",
      roles: ["mover"],
      avatar: p("1472099645785-5658abf4ff4e"),
    },
    {
      id: "u-deepak",
      name: "Deepak Shah",
      email: "deepak.mover@haulsy.test",
      password: DEMO_PASSWORD,
      phone: "905-555-0304",
      city: "Mississauga",
      roles: ["mover"],
      avatar: p("1519085360753-af0119f7cbe7"),
    },
    {
      id: "u-raj",
      name: "Raj Mehta",
      email: "raj.mover@haulsy.test",
      password: DEMO_PASSWORD,
      phone: "416-555-0305",
      city: "Toronto",
      roles: ["mover"],
      avatar: p("1560250097-0b93528c311a"),
    },
    {
      id: "u-ronak",
      name: "Ronak Desai",
      email: "ronak.mover@haulsy.test",
      password: DEMO_PASSWORD,
      phone: "604-555-0306",
      city: "Vancouver",
      roles: ["mover"],
      avatar: p("1492562080023-ab3db95bfbce"),
    },
    {
      id: "u-jay",
      name: "Jay Trivedi",
      email: "jay.mover@haulsy.test",
      password: DEMO_PASSWORD,
      phone: "403-555-0307",
      city: "Calgary",
      roles: ["mover"],
      avatar: p("1552058544-f2b08422138a"),
    },
    {
      id: "u-parth",
      name: "Parth Joshi",
      email: "parth.mover@haulsy.test",
      password: DEMO_PASSWORD,
      phone: "613-555-0308",
      city: "Ottawa",
      roles: ["mover"],
      avatar: p("1531427186611-ecfd6d936c79"),
    },
    {
      id: "u-drumil",
      name: "Drumil Shah",
      email: "drumil.mover@haulsy.test",
      password: DEMO_PASSWORD,
      phone: "416-555-0309",
      city: "Toronto",
      roles: ["mover"],
      avatar: p("1552374196-1ab2a1c593e8"),
    },
    {
      id: "u-dishant",
      name: "Dishant Rana",
      email: "dishant.mover@haulsy.test",
      password: DEMO_PASSWORD,
      phone: "905-555-0310",
      city: "Brampton",
      roles: ["mover"],
      avatar: p("1570295999919-56ceb5ecca61"),
    },
    {
      id: "u-krunal",
      name: "Krunal Shah",
      email: "krunal.mover@haulsy.test",
      password: DEMO_PASSWORD,
      phone: "604-555-0311",
      city: "Vancouver",
      roles: ["mover"],
      avatar: p("1566492031773-4f4e44671857"),
    },
    {
      id: "u-kushal",
      name: "Kushal Patel",
      email: "kushal.mover@haulsy.test",
      password: DEMO_PASSWORD,
      phone: "416-555-0312",
      city: "Toronto",
      roles: ["mover"],
      avatar: p("1633332755192-727a05c4013d"),
    },
    {
      id: "u-chintan",
      name: "Chintan Desai",
      email: "chintan.mover@haulsy.test",
      password: DEMO_PASSWORD,
      phone: "403-555-0313",
      city: "Calgary",
      roles: ["mover"],
      avatar: p("1599566150163-29194dcaad36"),
    },
  ],
  listings: [
    {
      id: "l-sofa-green",
      sellerId: "u-dharmesh",
      title: "Velvet 3-seater sofa",
      description:
        "Deep moss velvet, barely used. Smoke-free condo. Comes apart into two sections for the elevator. Pickup from a ground-floor unit near Queen West.",
      category: "sofa",
      photos: [
        "https://images.unsplash.com/photo-1555041469-a586c61ea9bc?auto=format&fit=crop&w=1400&q=80",
        "https://images.unsplash.com/photo-1540574163026-643ea20ade25?auto=format&fit=crop&w=1400&q=80",
      ],
      lengthCm: 220,
      widthCm: 90,
      heightCm: 80,
      weightKg: 48,
      price: 380,
      city: "Toronto",
      pickupAddress: "220 Queen St W, Toronto ON",
      status: "live",
      createdAt: "2026-08-10T09:00:00.000Z",
    },
    {
      id: "l-corner",
      sellerId: "u-dharmesh",
      title: "Linen corner sofa",
      description:
        "Generous L-shape in natural linen. Pet-free. Needs a large van — wrapping volume is just over 5 m³. Liberty Village, loading dock.",
      category: "sofa",
      photos: [
        "https://images.unsplash.com/photo-1493663284031-b7e3aefcae8e?auto=format&fit=crop&w=1400&q=80",
        "https://images.unsplash.com/photo-1540574163026-643ea20ade25?auto=format&fit=crop&w=1400&q=80",
      ],
      lengthCm: 280,
      widthCm: 220,
      heightCm: 85,
      weightKg: 92,
      price: 590,
      city: "Toronto",
      pickupAddress: "39 East Liberty St, Toronto ON",
      status: "live",
      createdAt: "2026-08-08T11:00:00.000Z",
    },
    {
      id: "l-table",
      sellerId: "u-joy",
      title: "Solid oak dining table",
      description:
        "Seats six. Legs unscrew. A few honest marks on the top. Pickup from a second-floor walk-up in Port Credit — two people recommended.",
      category: "table",
      photos: [
        "https://images.unsplash.com/photo-1615066390971-03e4e1c36ddf?auto=format&fit=crop&w=1400&q=80",
      ],
      lengthCm: 180,
      widthCm: 90,
      heightCm: 75,
      weightKg: 42,
      price: 160,
      city: "Mississauga",
      pickupAddress: "28 Lakeshore Rd E, Mississauga ON",
      status: "live",
      createdAt: "2026-08-12T14:20:00.000Z",
    },
    {
      id: "l-wardrobe",
      sellerId: "u-joy",
      title: "Two-door oak wardrobe",
      description:
        "Dismantles with an Allen key (included). Hanging rail and one shelf. Collection from Square One area.",
      category: "storage",
      photos: [
        "https://images.unsplash.com/photo-1595526114035-0d45ed16cfbf?auto=format&fit=crop&w=1400&q=80",
      ],
      lengthCm: 120,
      widthCm: 58,
      heightCm: 200,
      weightKg: 78,
      price: 200,
      city: "Mississauga",
      pickupAddress: "100 City Centre Dr, Mississauga ON",
      status: "live",
      createdAt: "2026-08-05T08:40:00.000Z",
    },
    {
      id: "l-fridge",
      sellerId: "u-priyenka",
      title: "Tall fridge freezer",
      description:
        "Frost-free, works perfectly. You'll want a van with a strap — 70 kg and 185 cm tall. Ground floor, driveway.",
      category: "appliance",
      photos: [
        "https://images.unsplash.com/photo-1571175443880-49e1d25b2bc5?auto=format&fit=crop&w=1400&q=80",
      ],
      lengthCm: 60,
      widthCm: 65,
      heightCm: 185,
      weightKg: 70,
      price: 120,
      city: "Brampton",
      pickupAddress: "2 Wellington St W, Brampton ON",
      status: "live",
      createdAt: "2026-08-14T16:00:00.000Z",
    },
    {
      id: "l-bed",
      sellerId: "u-dharmesh",
      title: "King oak bed frame",
      description:
        "Slatted king frame, no mattress. Flat-packs in 20 minutes. Light scuffs on one leg.",
      category: "bed",
      photos: [
        "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=1400&q=80",
      ],
      lengthCm: 200,
      widthCm: 160,
      heightCm: 40,
      weightKg: 35,
      price: 95,
      city: "Toronto",
      pickupAddress: "88 Dundas St E, Toronto ON",
      status: "reserved",
      createdAt: "2026-08-11T10:15:00.000Z",
    },
    {
      id: "l-drawers",
      sellerId: "u-priyenka",
      title: "Six-drawer pine chest",
      description:
        "Solid pine, recently oiled. Fits in a wagon if the seats go down — a van is easier.",
      category: "storage",
      photos: [
        "https://images.unsplash.com/photo-1556228453-efd6c1ff04f6?auto=format&fit=crop&w=1400&q=80",
      ],
      lengthCm: 80,
      widthCm: 45,
      heightCm: 120,
      weightKg: 38,
      price: 85,
      city: "Brampton",
      pickupAddress: "55 Queen St E, Brampton ON",
      status: "live",
      createdAt: "2026-08-09T12:00:00.000Z",
    },
    {
      id: "l-bike",
      sellerId: "u-joy",
      title: "Spin bike",
      description:
        "Quiet flywheel, adjustable seat. Heavy enough that you will want help on stairs. Second floor, elevator in the building.",
      category: "gym",
      photos: [
        "https://images.unsplash.com/photo-1517836357463-d25dfeac3438?auto=format&fit=crop&w=1400&q=80",
      ],
      lengthCm: 120,
      widthCm: 50,
      heightCm: 140,
      weightKg: 32,
      price: 145,
      city: "Mississauga",
      pickupAddress: "201 City Centre Dr, Mississauga ON",
      status: "live",
      createdAt: "2026-08-13T09:30:00.000Z",
    },
    {
      id: "l-armchair",
      sellerId: "u-dharmesh",
      title: "Boucle armchair",
      description:
        "Cream boucle, one owner. A car trunk will not cut it — wagon or van. Smoke-free.",
      category: "sofa",
      photos: [
        "https://images.unsplash.com/photo-1567538096630-e0c55bd6374c?auto=format&fit=crop&w=1400&q=80",
      ],
      lengthCm: 85,
      widthCm: 80,
      heightCm: 90,
      weightKg: 22,
      price: 185,
      city: "Toronto",
      pickupAddress: "12 Ossington Ave, Toronto ON",
      status: "sold",
      createdAt: "2026-08-15T18:00:00.000Z",
    },
    {
      id: "l-washer",
      sellerId: "u-meet",
      title: "9kg washing machine",
      description:
        "Three years old, serviced last month. Needs two people and a van with a dolly. Ground-floor kitchen, parking outside.",
      category: "appliance",
      photos: [
        "https://images.unsplash.com/photo-1626806787461-102c1bfaaea1?auto=format&fit=crop&w=1400&q=80",
      ],
      lengthCm: 60,
      widthCm: 60,
      heightCm: 85,
      weightKg: 68,
      price: 110,
      city: "Calgary",
      pickupAddress: "100 8 Ave SW, Calgary AB",
      status: "live",
      createdAt: "2026-08-07T13:45:00.000Z",
    },
    {
      id: "l-desk",
      sellerId: "u-meet",
      title: "Walnut standing desk",
      description:
        "Electric sit-stand, 160 cm wide. Frame separates from the top. Ideal for a van.",
      category: "table",
      photos: [
        "https://images.unsplash.com/photo-1518455027359-f3f8164ba6bd?auto=format&fit=crop&w=1400&q=80",
      ],
      lengthCm: 160,
      widthCm: 80,
      heightCm: 75,
      weightKg: 36,
      price: 250,
      city: "Calgary",
      pickupAddress: "225 6 Ave SW, Calgary AB",
      status: "live",
      createdAt: "2026-08-16T08:10:00.000Z",
    },
    {
      id: "l-shelf",
      sellerId: "u-dharmesh",
      title: "Industrial bookshelf",
      description:
        "Steel and oak, six shelves. Heavy but slim. Will go in a wagon if you take the shelves out.",
      category: "storage",
      photos: [
        "https://images.unsplash.com/photo-1594620302200-9a762244a156?auto=format&fit=crop&w=1400&q=80",
      ],
      lengthCm: 80,
      widthCm: 35,
      heightCm: 180,
      weightKg: 40,
      price: 125,
      city: "Toronto",
      pickupAddress: "480 University Ave, Toronto ON",
      status: "sold",
      createdAt: "2026-08-04T15:00:00.000Z",
    },
  ],
  movers: [
    {
      id: "m-aisha",
      userId: "u-aisha",
      vehicle: "van",
      capacityM3: 6,
      maxKg: 800,
      hourlyRate: 48,
      jobRate: 60,
      cities: ["Toronto", "Mississauga"],
      availability: weekdays,
      bio: "GTA weekdays. Blankets, straps and a folding trolley in the van. Careful on condo elevators.",
      photo: p("1573496359142-b8d87734a5a2"),
    },
    {
      id: "m-sagar",
      userId: "u-sagar",
      vehicle: "van",
      capacityM3: 6,
      maxKg: 800,
      hourlyRate: 45,
      jobRate: 55,
      cities: ["Toronto", "Brampton"],
      availability: weekdays,
      bio: "Ex-courier covering Toronto and Brampton. Two-person jobs welcome.",
      photo: p("1506794778202-cad84cf45f1d"),
    },
    {
      id: "m-chirag",
      userId: "u-chirag",
      vehicle: "van",
      capacityM3: 6,
      maxKg: 800,
      hourlyRate: 42,
      jobRate: 52,
      cities: ["Brampton", "Mississauga"],
      availability: weekdays,
      bio: "Peel region. I wrap furniture properly and take stairs slowly.",
      photo: p("1472099645785-5658abf4ff4e"),
    },
    {
      id: "m-deepak",
      userId: "u-deepak",
      vehicle: "large_van",
      capacityM3: 10,
      maxKg: 1200,
      hourlyRate: 55,
      jobRate: 80,
      cities: ["Mississauga", "Toronto"],
      availability: weekdays,
      bio: "Long-wheelbase van. Corner sofas and appliances across the west GTA.",
      photo: p("1519085360753-af0119f7cbe7"),
    },
    {
      id: "m-raj",
      userId: "u-raj",
      vehicle: "luton",
      capacityM3: 16,
      maxKg: 1400,
      hourlyRate: 65,
      jobRate: 120,
      cities: ["Toronto", "Mississauga", "Brampton"],
      availability: [...weekdays, { day: 0, start: "09:00", end: "14:00" }],
      bio: "Cube van with a lift gate. House moves and oversized loads.",
      photo: p("1560250097-0b93528c311a"),
    },
    {
      id: "m-ronak",
      userId: "u-ronak",
      vehicle: "van",
      capacityM3: 6,
      maxKg: 800,
      hourlyRate: 50,
      jobRate: 65,
      cities: ["Vancouver"],
      availability: weekdays,
      bio: "Vancouver weekdays. Tight downtown streets, I know the loading zones.",
      photo: p("1492562080023-ab3db95bfbce"),
    },
    {
      id: "m-jay",
      userId: "u-jay",
      vehicle: "large_van",
      capacityM3: 10,
      maxKg: 1200,
      hourlyRate: 52,
      jobRate: 75,
      cities: ["Calgary"],
      availability: weekdays,
      bio: "Calgary large van. Winter tires on, appliances a speciality.",
      photo: p("1552058544-f2b08422138a"),
    },
    {
      id: "m-parth",
      userId: "u-parth",
      vehicle: "van",
      capacityM3: 6,
      maxKg: 800,
      hourlyRate: 44,
      jobRate: 55,
      cities: ["Ottawa"],
      availability: weekdays,
      bio: "Ottawa and surrounding. Blankets and straps included.",
      photo: p("1531427186611-ecfd6d936c79"),
    },
    {
      id: "m-drumil",
      userId: "u-drumil",
      vehicle: "van",
      capacityM3: 6,
      maxKg: 800,
      hourlyRate: 46,
      jobRate: 58,
      cities: ["Toronto", "Brampton"],
      availability: [
        { day: 2, start: "08:00", end: "18:00" },
        { day: 3, start: "08:00", end: "18:00" },
        { day: 4, start: "08:00", end: "18:00" },
        { day: 5, start: "08:00", end: "18:00" },
        { day: 6, start: "08:00", end: "16:00" },
        { day: 0, start: "09:00", end: "15:00" },
      ],
      bio: "Tue–Sun in the GTA. I wrap like it is going on a stage.",
      photo: p("1552374196-1ab2a1c593e8"),
    },
    {
      id: "m-dishant",
      userId: "u-dishant",
      vehicle: "estate",
      capacityM3: 1.2,
      maxKg: 150,
      hourlyRate: 35,
      jobRate: 40,
      cities: ["Brampton", "Mississauga"],
      availability: weekends.concat([
        { day: 3, start: "17:00", end: "20:00" },
        { day: 4, start: "17:00", end: "20:00" },
      ]),
      bio: "Wagon / SUV. Evenings and weekends for bikes, drawers and compact pieces.",
      photo: p("1570295999919-56ceb5ecca61"),
    },
    {
      id: "m-krunal",
      userId: "u-krunal",
      vehicle: "luton",
      capacityM3: 16,
      maxKg: 1400,
      hourlyRate: 62,
      jobRate: 110,
      cities: ["Vancouver"],
      availability: weekdays,
      bio: "Vancouver cube van. House moves and oversized loads around the Lower Mainland.",
      photo: p("1566492031773-4f4e44671857"),
    },
    {
      id: "m-kushal",
      userId: "u-kushal",
      vehicle: "large_van",
      capacityM3: 10,
      maxKg: 1200,
      hourlyRate: 54,
      jobRate: 78,
      cities: ["Toronto", "Mississauga"],
      availability: weekdays,
      bio: "North York to Mississauga. Careful with condos and parking permits.",
      photo: p("1633332755192-727a05c4013d"),
    },
    {
      id: "m-chintan",
      userId: "u-chintan",
      vehicle: "van",
      capacityM3: 6,
      maxKg: 800,
      hourlyRate: 47,
      jobRate: 60,
      cities: ["Calgary"],
      availability: weekdays,
      bio: "Calgary weekdays. Straps, blankets, dolly.",
      photo: p("1599566150163-29194dcaad36"),
    },
  ],
  moveRequests: [
    {
      id: "mv-demo-1",
      customerId: "u-madhavi",
      fromAddress: "88 Dundas St E, Toronto ON",
      fromCity: "Toronto",
      toAddress: "55 Bloor St W, Toronto ON",
      toCity: "Toronto",
      loadPreset: "studio",
      notes: "Third floor walk-up at pickup. Parking booked 10–12.",
      when: { date: "2026-08-22", start: "10:00", end: "12:00" },
      createdAt: "2026-08-16T11:00:00.000Z",
    },
  ],
  bookings: [
    {
      id: "b-demo-pending",
      type: "marketplace",
      customerId: "u-madhavi",
      moverId: "u-aisha",
      listingId: "l-bed",
      slot: { date: "2026-08-21", start: "10:00", end: "12:00" },
      pickupAddress: "88 Dundas St E, Toronto ON",
      pickupCity: "Toronto",
      deliveryAddress: "12 Yonge St, Toronto ON",
      deliveryCity: "Toronto",
      pickup: { lat: 43.656, lng: -79.38, label: "88 Dundas St E, Toronto ON" },
      dropoff: { lat: 43.646, lng: -79.377, label: "12 Yonge St, Toronto ON" },
      distanceKm: 2.3,
      itemPrice: 95,
      haulFee: 60,
      serviceFee: 5,
      total: 160,
      paid: false,
      status: "pending",
      notes: "Stairs at pickup. Narrow hallway.",
      createdAt: "2026-08-18T09:00:00.000Z",
    },
    {
      id: "b-demo-1",
      type: "marketplace",
      customerId: "u-madhavi",
      moverId: "u-sagar",
      listingId: "l-armchair",
      slot: { date: "2026-08-21", start: "14:00", end: "16:00" },
      pickupAddress: "12 Ossington Ave, Toronto ON",
      pickupCity: "Toronto",
      deliveryAddress: "12 Yonge St, Toronto ON",
      deliveryCity: "Toronto",
      pickup: { lat: 43.646, lng: -79.42, label: "12 Ossington Ave, Toronto ON" },
      dropoff: { lat: 43.646, lng: -79.377, label: "12 Yonge St, Toronto ON" },
      distanceKm: 3.4,
      itemPrice: 185,
      haulFee: 55,
      serviceFee: 4,
      total: 244,
      paid: true,
      status: "assigned",
      notes: "Parking booked. Keys with neighbour.",
      createdAt: "2026-08-17T09:12:00.000Z",
    },
    {
      id: "b-demo-2",
      type: "move",
      customerId: "u-madhavi",
      moverId: "u-raj",
      moveRequestId: "mv-demo-1",
      slot: { date: "2026-08-22", start: "10:00", end: "12:00" },
      pickupAddress: "88 Dundas St E, Toronto ON",
      pickupCity: "Toronto",
      deliveryAddress: "55 Bloor St W, Toronto ON",
      deliveryCity: "Toronto",
      pickup: { lat: 43.656, lng: -79.38, label: "88 Dundas St E, Toronto ON" },
      dropoff: { lat: 43.67, lng: -79.39, label: "55 Bloor St W, Toronto ON" },
      distanceKm: 2.9,
      itemPrice: 0,
      haulFee: 195,
      serviceFee: 16,
      total: 211,
      paid: true,
      status: "en_route",
      notes: "Third floor walk-up at pickup. Parking booked 10–12.",
      createdAt: "2026-08-16T11:20:00.000Z",
    },
    {
      id: "b-demo-done",
      type: "marketplace",
      customerId: "u-madhavi",
      moverId: "u-kushal",
      listingId: "l-shelf",
      slot: { date: "2026-08-12", start: "12:00", end: "14:00" },
      pickupAddress: "480 University Ave, Toronto ON",
      pickupCity: "Toronto",
      deliveryAddress: "12 Yonge St, Toronto ON",
      deliveryCity: "Toronto",
      pickup: { lat: 43.656, lng: -79.389, label: "480 University Ave, Toronto ON" },
      dropoff: { lat: 43.646, lng: -79.377, label: "12 Yonge St, Toronto ON" },
      distanceKm: 1.8,
      itemPrice: 125,
      haulFee: 52,
      serviceFee: 4,
      total: 181,
      paid: true,
      status: "delivered",
      notes: "Item dismantles.",
      createdAt: "2026-08-10T11:00:00.000Z",
    },
  ],
  messages: [
    {
      id: "msg-1",
      bookingId: "b-demo-1",
      fromUserId: "u-madhavi",
      body: "Parking booked on Yonge from 14:00. Keys with the neighbour at 20.",
      createdAt: "2026-08-17T10:00:00.000Z",
    },
    {
      id: "msg-2",
      bookingId: "b-demo-1",
      fromUserId: "u-sagar",
      body: "Noted. Ossington has a loading zone — I’ll strap the chair in blankets.",
      createdAt: "2026-08-17T10:12:00.000Z",
    },
    {
      id: "msg-3",
      bookingId: "b-demo-pending",
      fromUserId: "u-madhavi",
      body: "Stairs at pickup, no elevator. The frame dismantles if that helps.",
      createdAt: "2026-08-18T09:05:00.000Z",
    },
  ],
  reviews: [],
};
